version: "3"
services:
  node:
    image: node:12-alpine
    container_name: typescript-enterprise-patterns
    tty: true
    volumes:
      - "../:/usr/src"
    working_dir: "/usr/src"
    command: npm i && npm test
